### ISSUE TITLE
question about Peptides-struct	

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [vijaydwivedi75/lrgb#1]
Hello,
Thank you for the nice code and timely dataset. I wonder as the label is of dimension 11, do you jointly predict all 11 features simultaneously, or do you predict each feature individually and then average MAE? Thank you!

**Comment by rampasek** [comment]
Hi @Chen-Cai-OSU,
We predict the 11 regression targets with a final MLP "prediction head" over the graph representation. During evaluation, these are then accumulated for the entire dataset and the overall MAE is computed. As every datapoint (a molecular graph) always has all 11 targets the order in which the average is computed doesn't matter (i.e. wether you average over dataset dimension first or over the 11 target dimension first).

I hope that answers your question!
Best, Ladislav
