### ISSUE TITLE
ModuleNotFoundError: No module named 'lrgb'

### ISSUE THREAD

**Issue by viktor-ktorvi** [vijaydwivedi75/lrgb#4]
Hi,

So I wanted to import this repo as a module. I installed it through conda as `pip install git+https://github.com/vijaydwivedi75/lrgb.git`.
I've done the same with the GraphGPS repo.

When I run this simple piece of code:
`import graphgps`
`import lrgb`

I get _ModuleNotFoundError: No module named 'lrgb'_. 

Notice that the `graphgps` module imports without problems which leads me to believe the problem is in the `lrgb` repo and for the life of me I cannot figure it out. 

I'd be very happy to get any suggestion. Thanks!

**Comment by vijaydwivedi75** [comment]
Hi @viktor-ktorvi, the LRGB datasets can be run in GraphGPS without importing additional `lrgb` module. The datasets are simply loaded using GraphGPS loaders (see [here](https://github.com/vijaydwivedi75/lrgb/blob/main/graphgps/loader/dataset/peptides_structural.py) for an example) and can be run using example commands from the root directory as mentioned [here](https://github.com/vijaydwivedi75/lrgb#running-graphgps).

**Comment by viktor-ktorvi** [comment]
Great! Thanks very much!
