### ISSUE TITLE
Questions about PascalVOC-SP and COCO-SP

### ISSUE THREAD

**Issue by HB-pencil-zero** [vijaydwivedi75/lrgb#7]
I found that the feature vector of these two datasets is 14-dimension, but when I read your paper ,  the description in this paper is " The initial feature of each superpixel node is 12 dimensional RGB feature value (mean, std, max, min) ". 
So I don't particularly understand why the features are actually fourteen-dimensional. Could you please explain to me? Thanks for your kindness.

**Comment by vijaydwivedi75** [comment]
Hi @HB-pencil-zero, thank you for pointing this out. 
The node feature vector is indeed 14-dimensional (12 dim RGB features + 2 dim coordinates) as mentioned in Table 1. 
The sentence that you refer to (in Section 3.1) misses to include the phrase about the 2 dimensional coordinate. We will correct this sentence and update the paper.

**Comment by HB-pencil-zero** [comment]
Thanks for your nice explaination and your kindness，and now I can understand the dataset.


***@***.***
***@***.***




---- Replied Message ----
From Vijay Prakash ***@***.***>Date 10/28/2022 21:41To ***@***.***>Cc Huang ***@***.******@***.***>Subject Re: [vijaydwivedi75/lrgb] Questions about PascalVOC-SP and COCO-SP (Issue #7)

Hi @HB-pencil-zero, thank you for pointing this out.
 The node feature vector is indeed 14-dimensional (12 dim RGB features + 2 dim coordinates) as mentioned in Table 1.
 The sentence that you refer to (in Section 3.1) misses to include the phrase about the 2 dimensional coordinate. We will correct this sentence and update the paper.
